recipes:
  train_rescoring_coop_x_fisc:
    input:
      dataset: coop_x_fisc
      chunked: False 
      select:
        query:
          constant_score: 
            filter:
              exists:
                field:
                  validation_done

    steps:
      - build_model:
          model:
            name: coop_fisc_ml
            method: RandomForestRegressor
            parameters:
              n_estimators: 20
              max_depth: 4
              min_samples_leaf: 5
            tries: 3
            test_size: 0.33
          numerical: .*(hit_score_(?!ml).*|population|surface)$
          #categorical: .*(matchid_location_countrycode)$
          target: validation_decision
